/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'h-yamashita' at '16/05/13 20:15' with Gradle 2.13
 *
 * @author h-yamashita, @date 16/05/13 20:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
